### ISSUE TITLE
Rename callbacks (questions 1 and 2)?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-array-methods-diagnostic#64]
sum -> reduceHandlerForSum
min -> reduceHandlerForMin

**Comment by MattB-GA-Boston** [comment]
This was definitely a stumbling point for students in the diagnostic. Maybe an example of actually using the callback would make things more clear?
e.g.
```
[1,2,3].reduce(min);
// => 1
```

**Comment by jrhorn424** [comment]
I'm not sure I like renaming the functions to `reduceHandlerForX`. I'll add commented examples and let's track confusion for this iteration, @berziiii and @payne-chris-r.

**Comment by gaand** [comment]
I added an example line in 912d7cfdf6c5920e7ef82e6455b30d2492da5c42

I don't know if this worked, but I agree with @jrhorn424 that renaming as proposed by me is not the answer.
