### ISSUE TITLE
Tests on master entirely out-of-sync with diagnostic

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-array-methods-diagnostic#89]
I have removed instructions to run `grunt test` for now.

**Comment by gaand** [comment]
A miscommunication when Lairen updated this diagnostic. Tests should be restored to master branch.

**Comment by laurenfazah** [comment]
Fixed! 🎉 @jrhorn424 @gaand

**Comment by gaand** [comment]
Refixed in 0fc984be4a1e7cedfaf2ab7faade4dd3ed7ef4f2
